Entites had to be redone
oEscal/tqs_project_2 pull request #13
Opened 2020-05-13 17:21 UTC by DrPunpun

2020-05-13 21:02 UTC, oEscal requested changes
resolve os conflitos primeiro

2020-05-15 17:57 UTC, oEscal requested changes
Adiciona também isto das relações á nova entidade de `List de Desejos`
Adiciona também os getters e setters

2020-05-15 17:57 UTC, oEscal commented on api/src/main/java/com/api/demo/models/ReportUser.java
> +    @JoinColumn(name = "to_user_id")
não falta no lado do User colocar a relação para aqui?

2020-05-15 17:57 UTC, oEscal commented on api/src/main/java/com/api/demo/models/ReportReviewGame.java
> +    private User author;
não falta no lado do User colocar a relação para aqui?

2020-05-15 17:57 UTC, oEscal commented on api/src/main/java/com/api/demo/models/ReportReviewGame.java
> +    private ReviewGame reported;
Não falta o correspondente do lado do ReviewGame?

2020-05-15 17:57 UTC, oEscal commented on api/src/main/java/com/api/demo/models/ReportReviewUser.java
> +    private ReviewUser reported;
Não falta o correspondente do lado do ReviewUser?

2020-05-15 20:26 UTC, DrPunpun commented on api/src/main/java/com/api/demo/models/ReportReviewGame.java
> +    private User author;
e tava

2020-05-15 20:33 UTC, DrPunpun commented on api/src/main/java/com/api/demo/models/ReportReviewGame.java
> +    private ReviewGame reported;
e tava

2020-05-15 20:39 UTC, DrPunpun commented on api/src/main/java/com/api/demo/models/ReportReviewUser.java
> +    private ReviewUser reported;
e tava

2020-05-15 23:05 UTC, oEscal commented on api/src/main/java/com/api/demo/models/ReportReviewGame.java
> +    private User author;
pois, este meti a mais sem querer, sorry

2020-05-15 23:42 UTC, oEscal approved these changes
podes dar merge no master depois de resolveres o conflito

2020-05-15 23:45 UTC, merged